server:
  port: 6100
  contextPath: /tng-vnv-lcm
app:
  lcm:
    bearer.token: none
  gk:
    host: gk
    base.url: http://${app.gk.host}:5000
    session:
      endpoint: ${app.gk.base.url}/sessions
      username: sonata
      password: 1234
  catalogue:
    host: tng-vnv-catalogue
    base.url: http://${app.catalogue.host}:6200
    package.metadata.endpoint: ${app.catalogue.base.url}/packages/{packageId}
    filter.test.endpoint: ${app.catalogue.base.url}/network-services/{networkServiceId}/matched-test-suites
    filter.ns.endpoint: ${app.catalogue.base.url}/test-suites/{testSuiteId}/matched-network-services
  trr:
    host: tng-vnv-trr
    base.url: http://${app.trr.host}:6300
    test.plan.create.endpoint: ${app.trr.base.url}/test-plans
    test.plan.update.endpoint: ${app.trr.base.url}/test-plans/{testPlanId}
  tpm:
    host: tng-vnv-tpm
    base.url: http://${app.tpm.host}:6400
    ns.deploy.endpoint: ${app.tpm.base.url}/test-plans/{testPlanId}/network-services/{networkServiceId}
    ns.destroy.endpoint: ${app.tpm.base.url}/test-plans/{testPlanId}/network-services/{networkServiceId}
  tee:
    host: tng-vnv-tee
    base.url: http://${app.tee.host}:6500
    suite.execute.endpoint: ${app.tee.base.url}/test-plans/{testPlanId}/network-services/{networkServiceId}/test-suites/{testSuiteId}