server:
  port: 6100
  contextPath: /tng-vnv-lcm
spring.jackson.property-naming-strategy: SNAKE_CASE
api:
  name: 5GTANGO VnV Platform Lifecycle Manager
  description: An H2020 5GTANGO project
  version: 0.0.1
  host: tng-vnv-lcm:6100
  terms.url: https://5gtango.eu/
  license:
    name: Apache License 2.0
    url: https://github.com/sonata-nfv/tng-vnv-lcm/blob/master/LICENSE
app:
  gk:
    host: gk
    base.url: http://qual-sp-bcn.5gtango.eu:32001/api/v2
    session:
      endpoint: ${app.gk.base.url}/sessions
      username: sonata
      password: 1234
  cat:
    host: tng-cat
    base.url: http://${app.cat.host}:4011/api/catalogues/v2
    package.metadata.endpoint: ${app.cat.base.url}/tests/{packageId}
    filter.test.endpoint: ${app.cat.base.url}/network-services/{serviceUuid}/matched-test-suites
    filter.ns.endpoint: ${app.cat.base.url}/test-suites/{testSuiteId}/matched-network-services
    list.ns.endpoint: ${app.gk.base.url}/services
  trr:
    host: tng-rep
    base.url: http://${app.trr.host}:4012/trr
    test.plan.create.endpoint: ${app.trr.base.url}/test-plans
    test.plan.update.endpoint: ${app.trr.base.url}/test-plans/{uuid}
  tpm:
    host: tng-vnv-tpm
    base.url: ${app.gk.base.url}
    ns.deploy.endpoint: ${app.tpm.base.url}/requests
    ns.status.endpoint: ${app.tpm.base.url}/requests/{requestId}
    ns.status.timeout.in.seconds: 60
    ns.get.endpoint: ${app.tpm.base.url}/requests/{serviceInstanceUuid}
    ns.destroy.endpoint: ${app.tpm.base.url}/requests
  tee:
    host: tng-vnv-tee
    base.url: http://${app.tee.host}:6200/tng-vnv-tee/api/v1
    suite.execute.endpoint: ${app.tee.base.url}/test-suite-results